module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  forceExit: true,
  roots: ['<rootDir>'],
  collectCoverage: true,
  setupFiles: ['<rootDir>/scripts/jest-setup.js'],
  cacheDirectory: '<rootDir>/.jest-cache',
  collectCoverageFrom: [
    'apps/**/*.ts',
    'apps/web/src/components/ProductImageInput.tsx',
    'packages/**/*.ts',
    '!**/*.d.ts',
    '!**/types.ts',
    '!**/*.config.ts',
    '!**/main.ts',
    '!**/app.module.ts',
    '!apps/**/dto/**',
    '!**/entities/**',
    '!**/interfaces/**',
    '!**/__tests__/**',
    '!**/?(*.)+(spec|test).[jt]s?(x)',
    '!**/*.e2e-spec.ts',
    '!**/test/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/.next/**',
    '!**/.next-dev/**',
    '!**/node_modules/**',
    '!apps/**/test-results/**',
    '!apps/**/e2e/**',
    '!packages/test-utils/**',
    '!apps/api/src/scratch_debug.ts',
    '!apps/api/src/test-bcrypt.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageThreshold: {
    global: {
      statements: 89,
      branches: 88,
      functions: 89,
      lines: 89,
    },
  },
  testEnvironment: 'node',
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/.next/',
    '/.next-dev/',
    '/e2e/',
    '/e2e-playwright-esm-test/',
    '/apps/desktop/tests/',
    '/.claude/',
    '/.claude/worktrees/',
    '/tests/',
    '/test/',
    '.*\\.e2e-spec\\.ts$',
    'apps[\\\\/]api[\\\\/]src[\\\\/]__tests__[\\\\/]db\\.mock\\.ts$'
  ],
  transform: {
    '^.+\\.(ts|tsx|js|jsx)$': ['ts-jest', {
      tsconfig: {
        rootDir: '.',
        baseUrl: '.',
        emitDecoratorMetadata: false,
        experimentalDecorators: true,
        ignoreDeprecations: '5.0',
        jsx: 'react-jsx',
        resolveJsonModule: true,
        paths: {
          '@smart-erp/database/schema': ['packages/database/src/schema/index.ts'],
          '@smart-erp/database/drizzle': ['packages/database/src/drizzle.ts'],
          '@smart-erp/database': ['packages/database/src/index.ts'],
          '@smart-erp/shared/data-contracts': ['packages/shared/src/data-contracts.ts'],
          '@smart-erp/shared/data-contract-registry': ['packages/shared/src/data-contract-registry.ts'],
          '@smart-erp/*': ['packages/*/src/index.ts'],
        },
      },
    }],
  },
  modulePathIgnorePatterns: [
    '/node_modules/',
    '/.claude/',
    '/.claude/worktrees/',
    '/dist/',
    '/build/',
    '/.next/',
    '/.next-dev/',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/apps/web/src/$1',
    '^@smart-erp/database/schema$': '<rootDir>/packages/database/src/schema/index.ts',
    '^@smart-erp/database/drizzle$': '<rootDir>/packages/database/src/drizzle.ts',
    '^@smart-erp/database$': '<rootDir>/packages/database/src/index.ts',
    '^@smart-erp/shared/data-contracts$': '<rootDir>/packages/shared/src/data-contracts.ts',
    '^@smart-erp/shared/data-contract-registry$': '<rootDir>/packages/shared/src/data-contract-registry.ts',
    '^@smart-erp/(.*)$': '<rootDir>/packages/$1/src/index.ts',
  },
};
