import sidebars from './sidebars';

describe('docs sidebars config', () => {
  it('uses generated docs navigation from the docs root', () => {
    expect(sidebars).toEqual({
      tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
    });
  });
});
