export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS',
  ORDER_INSUFFICIENT_STOCK = 'ORDER_INSUFFICIENT_STOCK',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  E_INVOICE_NOT_FOUND = 'E_INVOICE_NOT_FOUND',
  PURCHASE_ORDER_NOT_FOUND = 'PURCHASE_ORDER_NOT_FOUND',
  LEAD_NOT_FOUND = 'LEAD_NOT_FOUND',
  DEAL_NOT_FOUND = 'DEAL_NOT_FOUND',
  FIXED_ASSET_NOT_FOUND = 'FIXED_ASSET_NOT_FOUND',
  LOT_NOT_FOUND = 'LOT_NOT_FOUND',
  TRANSFER_NOT_FOUND = 'TRANSFER_NOT_FOUND',
  CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
  EXCHANGE_RATE_NOT_FOUND = 'EXCHANGE_RATE_NOT_FOUND',
  APPROVAL_REQUEST_NOT_FOUND = 'APPROVAL_REQUEST_NOT_FOUND',
  APPROVAL_RULE_NOT_FOUND = 'APPROVAL_RULE_NOT_FOUND',
  PRODUCTION_ORDER_NOT_FOUND = 'PRODUCTION_ORDER_NOT_FOUND',
  KPI_TARGET_NOT_FOUND = 'KPI_TARGET_NOT_FOUND',
  PAYROLL_BOARD_NOT_FOUND = 'PAYROLL_BOARD_NOT_FOUND',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT',
  INVENTORY_ADJUSTMENT_FAILED = 'INVENTORY_ADJUSTMENT_FAILED',
  IDEMPOTENCY_REPLAY = 'IDEMPOTENCY_REPLAY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  DUPLICATE_ENTITY = 'DUPLICATE_ENTITY',
  INVALID_OPERATION = 'INVALID_OPERATION',
}

export const ErrorMessages: Record<ErrorCode, string> = {
  [ErrorCode.INTERNAL_ERROR]: 'Internal server error',
  [ErrorCode.VALIDATION_ERROR]: 'Validation failed',
  [ErrorCode.NOT_FOUND]: 'Resource not found',
  [ErrorCode.CONFLICT]: 'Resource conflict',
  [ErrorCode.FORBIDDEN]: 'Access denied',
  [ErrorCode.UNAUTHORIZED]: 'Unauthorized',
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 'Token has expired',
  [ErrorCode.AUTH_TOKEN_REVOKED]: 'Token has been revoked',
  [ErrorCode.TENANT_REQUIRED]: 'Tenant ID is required',
  [ErrorCode.TENANT_NOT_FOUND]: 'Tenant not found',
  [ErrorCode.ORDER_NOT_FOUND]: 'Order not found',
  [ErrorCode.ORDER_INVALID_STATUS]: 'Invalid order status transition',
  [ErrorCode.ORDER_INSUFFICIENT_STOCK]: 'Insufficient stock for order',
  [ErrorCode.PAYMENT_FAILED]: 'Payment processing failed',
  [ErrorCode.PRODUCT_OUT_OF_STOCK]: 'Product is out of stock',
  [ErrorCode.PRODUCT_NOT_FOUND]: 'Product not found',
  [ErrorCode.CUSTOMER_NOT_FOUND]: 'Customer not found',
  [ErrorCode.SUPPLIER_NOT_FOUND]: 'Supplier not found',
  [ErrorCode.USER_NOT_FOUND]: 'User not found',
  [ErrorCode.ROLE_NOT_FOUND]: 'Role not found',
  [ErrorCode.EMPLOYEE_NOT_FOUND]: 'Employee not found',
  [ErrorCode.WAREHOUSE_NOT_FOUND]: 'Warehouse not found',
  [ErrorCode.PROJECT_NOT_FOUND]: 'Project not found',
  [ErrorCode.INVOICE_NOT_FOUND]: 'Invoice not found',
  [ErrorCode.E_INVOICE_NOT_FOUND]: 'E-Invoice not found',
  [ErrorCode.PURCHASE_ORDER_NOT_FOUND]: 'Purchase order not found',
  [ErrorCode.LEAD_NOT_FOUND]: 'Lead not found',
  [ErrorCode.DEAL_NOT_FOUND]: 'Deal not found',
  [ErrorCode.FIXED_ASSET_NOT_FOUND]: 'Fixed asset not found',
  [ErrorCode.LOT_NOT_FOUND]: 'Lot not found',
  [ErrorCode.TRANSFER_NOT_FOUND]: 'Transfer not found',
  [ErrorCode.CURRENCY_NOT_FOUND]: 'Currency not found',
  [ErrorCode.EXCHANGE_RATE_NOT_FOUND]: 'Exchange rate not found',
  [ErrorCode.APPROVAL_REQUEST_NOT_FOUND]: 'Approval request not found',
  [ErrorCode.APPROVAL_RULE_NOT_FOUND]: 'Approval rule not found',
  [ErrorCode.PRODUCTION_ORDER_NOT_FOUND]: 'Production order not found',
  [ErrorCode.KPI_TARGET_NOT_FOUND]: 'KPI target not found',
  [ErrorCode.PAYROLL_BOARD_NOT_FOUND]: 'Payroll board not found',
  [ErrorCode.MESSAGE_NOT_FOUND]: 'Message not found',
  [ErrorCode.COMMENT_NOT_FOUND]: 'Comment not found',
  [ErrorCode.INVENTORY_INSUFFICIENT]: 'Insufficient inventory',
  [ErrorCode.INVENTORY_ADJUSTMENT_FAILED]: 'Inventory adjustment failed',
  [ErrorCode.IDEMPOTENCY_REPLAY]: 'Request already processed',
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 'Too many requests, please try again later',
  [ErrorCode.INTEGRATION_ERROR]: 'External integration failed',
  [ErrorCode.DUPLICATE_ENTITY]: 'Entity already exists',
  [ErrorCode.INVALID_OPERATION]: 'Operation not allowed in current state',
};
